"""Step 5 (CSD3 or laptop): collect step-3 outputs into the committed tables.

    python directions/d7_partitioned_prs/code/05_collect.py [--work <dir>]

Reads work/partition/*.tsv (summary statistics only -- no per-subject values)
and writes to results/:
    table_d7_partition.tsv   every arm x outcome x set row
    table_d7_pairs.tsv       paired contrasts (K2, K3, S1-S4)
    table_d7_primary.tsv     the pre-registered readout (below), with Bonferroni
    SUMMARY.md               the primary table as markdown + the gates

Pre-registered readout (README.md "Pre-registration"): matched cells only
(SCZ25_META and MDD_pooled -> pooled; SCZ25_EUR, MDD_eur and EA -> EUR),
HCP-MMP global_slope_1lmm, primary sets K1c, K2 x2, K3 x2 and the K2 and K3
pairs: 7 tests per arm.  Bonferroni over those 7 within arm (p_ER, p_null).
Pooled is the primary cell; EUR is the replication.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parents[1]
PRIMARY_SETS = ["K1c_not_brain_expressed", "K2_neuronal", "K2_glial", "K3_syngo", "K3_oligodendrocyte"]
PRIMARY_PAIRS = ["K2", "K3"]


def md(df: pd.DataFrame) -> str:
    """Markdown table without the optional `tabulate` dependency."""
    f = lambda v: "" if (isinstance(v, float) and np.isnan(v)) else (f"{v:.4g}" if isinstance(v, float) else str(v))
    head = "| " + " | ".join(df.columns) + " |"
    rule = "|" + "|".join([":--"] * df.shape[1]) + "|"
    return "\n".join([head, rule] + ["| " + " | ".join(f(v) for v in r) + " |" for r in df.itertuples(index=False)])


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", default=str(HERE / "work"))
    a = ap.parse_args()
    pdir = Path(a.work) / "partition"
    R = HERE / "results"; R.mkdir(exist_ok=True)
    main_f = sorted(f for f in pdir.glob("*.tsv") if not f.name.endswith("__pairs.tsv"))
    pair_f = sorted(pdir.glob("*__pairs.tsv"))
    assert main_f, f"no step-3 outputs in {pdir}"
    T = pd.concat([pd.read_csv(f, sep="\t") for f in main_f], ignore_index=True)
    P = pd.concat([pd.read_csv(f, sep="\t") for f in pair_f], ignore_index=True)
    T.to_csv(R / "table_d7_partition.tsv", sep="\t", index=False, float_format="%.5g")
    P.to_csv(R / "table_d7_pairs.tsv", sep="\t", index=False, float_format="%.5g")

    sel = (T.outcome_set == "imaging_hcp") & (T.outcome == "global_slope_1lmm") & T.set.isin(PRIMARY_SETS)
    A = T[sel][["arm", "cell", "set", "n", "n_genes", "full_beta", "full_p", "er_interpretable",
                "beta", "p", "f", "f_enrich", "p_f", "ER", "ER_lo", "ER_hi",
                "ER_null_med", "ER_rel", "p_ER"]].copy()
    A["test"] = A.set
    A["p_test"] = A.p_ER
    selp = (P.outcome_set == "imaging_hcp") & (P.outcome == "global_slope_1lmm") & P.contrast.isin(PRIMARY_PAIRS)
    B = P[selp].copy()
    B["test"] = B.set_a + " - " + B.set_b
    B["p_test"] = B.p_null
    K = pd.concat([A, B[["arm", "cell", "test", "dER", "dER_lo", "dER_hi", "p_test", "er_interpretable"]]],
                  ignore_index=True)
    K["n_tests"] = K.groupby("arm").test.transform("count")
    K["p_bonf"] = np.minimum(1, K.p_test * K.n_tests)
    K.to_csv(R / "table_d7_primary.tsv", sep="\t", index=False, float_format="%.5g")

    gate = pd.read_csv(R / "table_d7_score_gate.tsv", sep="\t") if (R / "table_d7_score_gate.tsv").exists() else None
    lines = ["# D7 partitioned SBayesRC scores: primary readout", "",
             "Generated by `code/05_collect.py`; do not edit by hand. HCP-MMP `global_slope_1lmm`, matched cells.",
             "ER is read against its matched null (`ER_null_med`), not 1; `ER_rel` = ER / null median.",
             "ER is only interpretable where the full score predicts the outcome (`er_interpretable`).", ""]
    show = K[["arm", "cell", "test", "full_beta", "full_p", "beta", "f_enrich", "p_f", "ER", "ER_lo",
              "ER_hi", "ER_rel", "dER", "dER_lo", "dER_hi", "p_test", "p_bonf", "er_interpretable"]]
    lines.append(md(show))
    if gate is not None:
        lines += ["", "## Step-2 gate (row sums vs Figure-1 .profile)", "", md(gate)]
    gd = T.groupby(["arm", "outcome_set", "outcome"]).gate_dbeta_vs_lmer.first().dropna()
    if len(gd):
        lines += ["", "## Step-3 gate (OLS full-score beta minus step-9 lmer beta; pass if |diff| < 0.005)", "",
                  md(gd.reset_index())]
    (R / "SUMMARY.md").write_text("\n".join(lines) + "\n")
    print(show.round(3).to_string(index=False))


if __name__ == "__main__":
    main()
